name: Generate OpenApi Spec

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  spec_gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spec
        uses: actions/checkout@v2

      - name: Validate spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "validate spec/xatal.yaml"

      - name: Build spec
        uses: mpetrunic/swagger-cli-action@v1.0.0
        with:
          command: "bundle -o spec.yaml -t yaml spec/xatal.yaml"

      - name: Publish spec
        uses: Legion2/swagger-ui-action@v1
        with:
          output: specs
          spec-file: spec.yaml

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.EDSON_GITHUB_TOKEN }}
          publish_dir: specs
